# using official Node runtime as parent image
FROM node:18

# set working directory to /app
WORKDIR /app

# copy package.json and packag-lock to working directory
COPY package*.json ./

# Install ffmpeg in the container
RUN apt-get update && apt-get install -y ffmpeg

# Install any needed packages specified in package.json
RUN npm install

# Copy app source inside docker image
COPY . .

# Make port 3000 available outside this container
EXPOSE 3000

# Define command to run your app using CMD (only one CMD allowed)
CMD [ "npm", "start"]